project:
  type: website

website:
  title: "Ryan Baker"
  page-footer: "Copyright © 2025 Ryan Baker"
  navbar:
    title: Ryan Baker
    left:
      - href: teaching/
        text: Teaching
      - href: projects/
        text: Projects
      
format:
  html:
    theme: [united, styles.scss]
