baseURL = 'https://rybkr.com/'
locale = 'en-us'
title = 'Ryan Baker'
theme = "PaperMod"
publishDir = "docs"

[outputs]
home = ["HTML", "JSON"]

[markup]
  [highlight]
    codeFences = true
    lineNos = true
    noClasses = false
    guessSyntax = true
    style = ""

[params]
  ShowCodeCopyButtons = true
  author = "Ryan Baker"

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 1

[[menu.main]]
name = "Library"
url = "/library/"
weight = 2

[[menu.main]]
name = "Resume"
url = "/resume/"
weight = 3
