---
title: "Ryan Baker"
subtitle: Ideas are bulletproof
about:
  template: solana
  image-shape: round
  links:
    - icon: github
      text: Github
      href: https://github.com/rybkr
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/ryanbaker1228
---

Howdy! I am Ryan.

I am a computer engineering student at Purdue University.
At Purdue, I balance coursework with teaching (both formally and informally), serving on the IEEE executive board, and working on projects that help people.

When I'm offline, you can find me playing chess, training Brazilian Jiu-Jitsu, or playing guitar.


## Education

**Bachelor of Science in Computer Engineering**  
Purdue University  
West Lafayette, Indiana | Aug 2023 - May 2026

## Experience

**Course Instructor** | Purdue University | Jan 2025 - Present
- Developing accessible curricula and delivering lectures in a unique style

**Embedded Software Engineering Intern** | Matrix Design Group | May 2025 - Aug 2025
- Designed and implemented a space-efficient logging system for embedded platforms
- Improved developer workflows with lightweight visualization and analysis tools

**Teaching Assistant** | Purdue University | Aug 2024 - Dec 2024
- Assisted students in completing programming assignments on Linux and bash scripting
- Hosted weekly office hours to provide support and guidance to students
